# Generated by Django 4.1 on 2022-08-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_cor_modelo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="marca",
            options={"verbose_name_plural": "Marcas"},
        ),
    ]
